# predict salaries

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df.isnull().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [6]:
#fill in the empty values of experience with zero
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
!pip install word2number


In [7]:
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [27]:
import math
mean_score = math.floor(df['test_score(out of 10)'].mean())
mean_score

7

In [29]:

#fill in the empty values of test_score with median
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [30]:
#Linear Regression
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [31]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [32]:
reg.intercept_

17237.330313727165

# 5 years experience, test score -10 , interview score-8

In [36]:
reg.predict([[5,10,8]])

array([68080.68334762])

In [37]:
#mx1+mx2+mx3+b
2827.63404314*5+ 1912.93803053*10+ 2196.9753141*8+17237.330313727165

68080.68334752717

# 0 years experience, test score -5 , interview score-5

In [39]:
reg.predict([[0,5,5]])

array([37786.89703692])

In [40]:
# mx1+mx2+mx3+b
2827.63404314*0+ 1912.93803053*5+ 2196.9753141*5+17237.330313727165

37786.89703687717